version: "3.2"
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "laraapp_db"
      # MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./.docker/.db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000 mode=debug
    image: "laravelapp"
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
